### ISSUE TITLE
DB finally running, now I can't make plumber work

### ISSUE THREAD

**Issue by pachadotdev** [pachamaltese/tradestatistics-plumber-api#1]
Hi !!

The server now has the full DB and I installed both RStudio Server and these R packages as root (so those are available for all users):
* RPostgreSQL
* tidyverse
* jsonlite
* plumber
* glue

The script on this repo was an attempt to run an SQL query and convert the result to JSON. My 1st test was:

```r
> library(plumber)
> api <- plumb("api.R")
Loading required package: DBI
> api$run(port = 8000)
Starting server to listen on port 8000
Running the swagger UI at http://127.0.0.1:8000/__swagger__/
```

The output returns:
```
pacha@tradestatistics:~$ curl "http://localhost:8000/echo"
{"msg":["The message is: ''"]}
pacha@tradestatistics:~$ curl "http://localhost:8000/yrpc?y=2015"
["{}"]
```
while RStudio returns:
```r
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  invalid byte sequence for encoding "UTF8": 0xb9
)
Warning in postgresqlQuickSQL(conn, statement, ...) :
  Could not create execute: 
```

Can you give me a hand? You can always go to `data.local:8787` and open RStudio Server :)

**Comment by aedobbyn** [comment]
I wasn't able to connect to the db using a `dbusr` of either `"amanda/jorge/joshua"` or just `"amanda"`.

```
Error in postgresqlNewConnection(drv, ...) : 
  RS-DBI driver: (could not connect amanda@data.local:5432 on dbname "trade_statistics": FATAL:  password authentication failed for user "amanda"
)
```

Any ideas?

As for the error you're getting, I'm not totally sure but you might try using [`glue::glue_sql`](https://glue.tidyverse.org/reference/glue_sql.html) instead of `sprintf` to avoid any encoding errors.

**Comment by pachadotdev** [comment]
Hi @aedobbyn 
Thanks for the prompt reply!! On this repo I have a `.Renviron` file that I didn't upload, this is the content of that file:

```
dbusr="amanda"
dbpwd="YOUR_PASSWORD"
dbhost="localhost"
dbname="trade_statistics"
```

**Comment by pachadotdev** [comment]
@aedobbyn glue works !!!!!!!!!!! *thanks a lot for the suggestion*

![image](https://user-images.githubusercontent.com/10091065/49966558-10fe0a80-feff-11e8-8c19-2fbb85b497f9.png)

**Comment by pachadotdev** [comment]
@aedobbyn I just double checked your permissions again, it should work now

**Comment by aedobbyn** [comment]
These creds seem to be referencing a local copy of the database, which I don't have -- shouldn't we be accessing the remote db?

**Comment by pachadotdev** [comment]
You're right! I was able to connect to the DB in the server with all users
from my laptop by using datagrip
Just in case I reseted the passwords
Please let me know if it works
